### ISSUE TITLE
api 메뉴에서 deprecate 속성 오류

### ISSUE THREAD

**Issue by onlydel** [realgrid/realgrid.github.com#17]
deprecate가 아닌 항목들에 deprecate 태그가 들어간것 같습니다.

[/api/getGroupNames/](/api/getGroupNames/)
[/api/getRowData/](/api/getRowData/)

등등

`deprecated: true`가 메타정보에 들어가면 메뉴에서 빨간색 아이콘이 표시되도록 되어 있습니다.
주의가 필요합니다.

**Comment by jungjun88** [comment]
정상적인 deprecated
